[package]
name = "cubic-platform"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
winit = { workspace = true, features = ["rwh_06"] }
anyhow = { workspace = true }
tracing = { workspace = true }
