[package]
name = "cubic-core"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
