#!/usr/bin/env python3
"""Regenerate games/cubic-game/assets/models/highlight.obj — a wireframe
cube (12 thin edge bars) used to highlight the block the player is looking
at. Local origin is the block's min corner; the mesh spans slightly outside
one voxel so it doesn't z-fight the block's own faces. Re-run this if the
proportions (VOXEL_SIZE, inflation, bar thickness) ever need to change.
"""

size = 0.5  # VOXEL_SIZE
pad = 0.006  # outward inflation
thick = 0.03  # edge bar cross-section width

lo = -pad
hi = size + pad
t = thick

verts = []
norms = []
uvs = []
faces = []  # each: list of (vi, ti, ni) 1-indexed, per triangle


def add_box(x0, x1, y0, y1, z0, z1):
    base = len(verts)
    corners = [
        (x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
        (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1),
    ]
    verts.extend(corners)
    face_defs = [
        ((0, 0, -1), [0, 3, 2, 1]),  # -Z (front)
        ((0, 0, 1), [5, 6, 7, 4]),  # +Z (back)
        ((-1, 0, 0), [4, 7, 3, 0]),  # -X (left)
        ((1, 0, 0), [1, 2, 6, 5]),  # +X (right)
        ((0, 1, 0), [3, 7, 6, 2]),  # +Y (top)
        ((0, -1, 0), [4, 0, 1, 5]),  # -Y (bottom)
    ]
    nbase = len(norms)
    for n, _ in face_defs:
        norms.append(n)
    ubase = len(uvs)
    uvs.extend([(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)])
    for fi, (n, idx) in enumerate(face_defs):
        ni = nbase + fi + 1
        quad = [(base + idx[k] + 1, ubase + k + 1, ni) for k in range(4)]
        faces.append([quad[0], quad[2], quad[1]])
        faces.append([quad[0], quad[3], quad[2]])


for y0, y1 in [(lo, lo + t), (hi - t, hi)]:
    for z0, z1 in [(lo, lo + t), (hi - t, hi)]:
        add_box(lo, hi, y0, y1, z0, z1)
for x0, x1 in [(lo, lo + t), (hi - t, hi)]:
    for z0, z1 in [(lo, lo + t), (hi - t, hi)]:
        add_box(x0, x1, lo, hi, z0, z1)
for x0, x1 in [(lo, lo + t), (hi - t, hi)]:
    for y0, y1 in [(lo, lo + t), (hi - t, hi)]:
        add_box(x0, x1, y0, y1, lo, hi)

out_path = "games/cubic-game/assets/models/highlight.obj"
with open(out_path, "w") as f:
    f.write("# CubicEngine block-highlight wireframe cube\n")
    f.write("# 12 thin edge bars forming a cube outline, slightly inflated\n")
    f.write("# outward from a unit voxel so it doesn't z-fight the block's\n")
    f.write("# own faces. Local origin = block's min corner (matches how\n")
    f.write("# world block positions are computed from chunk-local indices).\n")
    f.write("# Procedurally generated by this script — re-run to regenerate.\n\n")
    f.write("# Vertices\n")
    for v in verts:
        f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
    f.write("\n# Normals\n")
    for n in norms:
        f.write(f"vn {n[0]:.1f} {n[1]:.1f} {n[2]:.1f}\n")
    f.write("\n# UVs\n")
    for u in uvs:
        f.write(f"vt {u[0]:.1f} {u[1]:.1f}\n")
    f.write("\n# Faces\n")
    for tri in faces:
        f.write("f " + " ".join(f"{vi}/{ti}/{ni}" for vi, ti, ni in tri) + "\n")

print(f"wrote {out_path}: {len(verts)} verts, {len(faces)} triangles")
